# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-13 00:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PosYamantaka', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='descripcion',
            field=models.TextField(null=True),
        ),
    ]
