# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-13 22:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('PosYamantaka', '0002_auto_20170313_0002'),
    ]

    operations = [
        migrations.CreateModel(
            name='Discount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('porcentaje_descuento', models.PositiveIntegerField()),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PosYamantaka.Category')),
            ],
        ),
        migrations.CreateModel(
            name='Society',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('valor_anual', models.DecimalField(decimal_places=2, max_digits=100)),
                ('valor_semestral', models.DecimalField(decimal_places=2, max_digits=100)),
                ('valor_mensual', models.DecimalField(decimal_places=2, max_digits=100)),
                ('categorias', models.ManyToManyField(through='PosYamantaka.Discount', to='PosYamantaka.Category')),
            ],
        ),
        migrations.AddField(
            model_name='discount',
            name='society',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PosYamantaka.Society'),
        ),
        migrations.AlterUniqueTogether(
            name='discount',
            unique_together=set([('society', 'category')]),
        ),
    ]
